# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3ef6f384be5e00af8a08c7a11618c9e5a472d3797cfa3873957cefd65d55ba766905536ff6ff01f44c4f80e3fd5067b8bb9fa16b8d07a3c535b043cd453fdade

test:
  secret_key_base: 2a9a1fc47f5f3c4998fd12068f6a7cc5e1d304975d0db4032c7c01be63b14f59eacc6e5b07a072964336a9eb6e731e2b712350568dd3e40e5a0d5bfad4261f3e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
